### ISSUE TITLE
bug: plugin crashes on IDE startup

### ISSUE THREAD

**Issue by zenshixd** [FalsePattern/ZigBrains#23]
hi

I am having issues with ZigBrains when opening bun repo (https://github.com/oven-sh/bun). It throws and error on startup, and doesnt provide any highlights.

IDE version: 
IntelliJ IDEA 2023.2.5 (Ultimate Edition)
Build #IU-232.10227.8, built on November 9, 2023

Error:
```
java.lang.NullPointerException: Parameter specified as non-null is null: method com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getAllEditors, parameter file
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getAllEditors(FileEditorManagerImpl.kt)
	at com.falsepattern.zigbrains.lsp.utils.FileUtils.lambda$getAllOpenedEditorsForVirtualFile$1(FileUtils.java:93)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.falsepattern.zigbrains.lsp.utils.ApplicationUtils.computableReadAction(ApplicationUtils.java:55)
	at com.falsepattern.zigbrains.lsp.utils.FileUtils.getAllOpenedEditorsForVirtualFile(FileUtils.java:91)
	at com.falsepattern.zigbrains.lsp.utils.FileUtils.getAllOpenedEditorsForUri(FileUtils.java:87)
	at com.falsepattern.zigbrains.lsp.client.languageserver.wrapper.LanguageServerWrapper.connect(LanguageServerWrapper.java:778)
	at com.falsepattern.zigbrains.lsp.client.languageserver.wrapper.LanguageServerWrapper.reconnect(LanguageServerWrapper.java:681)
	at com.falsepattern.zigbrains.lsp.client.languageserver.wrapper.LanguageServerWrapper.crashed(LanguageServerWrapper.java:647)
	at com.falsepattern.zigbrains.lsp.editor.EditorEventManager.inlayHint(EditorEventManager.java:1396)
	at com.falsepattern.zigbrains.lsp.contributors.LSPInlayHintProvider$LSPInlayHintsCollector.collectHintsForFile(LSPInlayHintProvider.java:76)
	at com.intellij.codeInsight.hints.declarative.impl.DeclarativeInlayHintsPass.doCollectInformation(DeclarativeInlayHintsPass.kt:40)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:390)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:77)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:24)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:386)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:377)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:376)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:352)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:350)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

ZLS version: 0.11.0

Is it known issue? if so how to fix that?

**Comment by FalsePattern** [comment]
Should be fixed in 0.9.0, the LSP was initializing too eagerly even when the project was not completely loaded yet.
