### ISSUE TITLE
Null pointer on start up

### ISSUE THREAD

**Issue by ChargeIn** [FalsePattern/ZigBrains#38]
The issue occurred since the last update.

java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because the return value of "com.falsepattern.zigbrains.zig.environment.ZLSConfig.zig_exe_path()" is null
	at com.falsepattern.zigbrains.zig.lsp.ZLSStartupActivity.lambda$initZLS$1(ZLSStartupActivity.java:77)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

the zig commend zig env works fine and the binary path is working fine.

**Comment by FalsePattern** [comment]
Fixed in 13.0.1 (hotfix release, replaces 13.0.0)
