### ISSUE TITLE
com.intellij.diagnostic.PluginException: Intention Description Dir URL is null: Convert to multiline; MakeStringMultiline; while looking for description.html [Plugin: com.falsepattern.zigbrains]

### ISSUE THREAD

**Issue by danny-su** [FalsePattern/ZigBrains#73]
com.intellij.diagnostic.PluginException: Intention Description Dir URL is null: Convert to multiline; MakeStringMultiline; while looking for description.html [Plugin: com.falsepattern.zigbrains]
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getResourceLocation(IntentionActionMetaData.java:62)
	at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:132)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings$IntentionSearchableOptionContributor.processOptions(IntentionManagerSettings.kt:93)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.lambda$initialize$0(SearchableOptionsRegistrarImpl.java:125)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:61)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.initialize(SearchableOptionsRegistrarImpl.java:125)
	at com.intellij.openapi.options.newEditor.SettingsFilter.lambda$new$1(SettingsFilter.java:61)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by FalsePattern** [comment]
Fixed in 19.3.0
